### ISSUE TITLE
ros melodic 在 gazebo 中仿真 aubo_i5 机器人发生错误

### ISSUE THREAD

**Issue by dashuaip** [AuboRobot/aubo_ros_driver#2]
按照README中的指令进行
第一步：roslaunch aubo_gazebo aubo_bringup.launch robot_model:=aubo_i5
（1）成功打开，但是报出以下错误
```
[ERROR] [1704515763.271079109, 0.372000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/shoulder_joint
[ERROR] [1704515763.271690508, 0.372000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/foreArm_joint
[ERROR] [1704515763.272205575, 0.372000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/upperArm_joint
[ERROR] [1704515763.272666852, 0.372000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wrist1_joint
[ERROR] [1704515763.273475825, 0.372000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wrist2_joint
[ERROR] [1704515763.274054572, 0.372000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wrist3_joint
```
![image](https://github.com/AuboRobot/aubo_ros_driver/assets/130347165/428ce5d6-2141-4710-877d-ab3ca1de1a00)

第二步：roslaunch aubo_moveit_config moveit_planning_execution.launch sim:=true robot_model:=aubo_i5
（1）报错，没有在aubo_moveit_config/config文件夹中找到aubo_i5.sdf
```
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 157, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 634, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 634, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 679, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 271, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/loader.py", line 476, in param_value
    with open(textfile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/fy/aubo_new_ws/src/aubo_ros_driver/aubo_moveit_config/config/aubo_i5.srdf'
```
![image](https://github.com/AuboRobot/aubo_ros_driver/assets/130347165/15a1bb29-c16d-4518-80c9-024228d5a360)

（2）因此，我从aubo_description文件中找到aubo_i5.srdf并把它粘贴到了aubo_moveit_config/config文件夹下
（3）再次运行，提示”You can start planning now!“  但是其中有报错提示和警告
```
[ERROR] [1704516469.424301604]: Semantic description is not specified for the same robot as the URDF
[ WARN] [1704516469.425082470]: Skipping virtual joint 'FixedBase' because its child frame 'base_link' does not match the URDF frame 'world'
[ WARN] [1704516469.470237393]: IK plugin for group 'manipulator_i5' relies on deprecated API. Please implement initialize(RobotModel, ...).
```
![image](https://github.com/AuboRobot/aubo_ros_driver/assets/130347165/b6123413-dfe7-4514-8663-75f16ffb0983)

第三步：roslaunch aubo_moveit_config moveit_rviz.launch
（1）成功打开了rviz，但是和第二步（3）有同样的报错提示和警告
（2）尝试plan&execute机械臂，rviz提示Failed，第二步打开的终端报错
```
[ WARN] [1704516887.852870316, 1122.695000000]: Unable to find a valid state nearby the start state (using jiggle fraction of 0.050000 and 100 sampling attempts). Passing the original planning request to the planner.
[ INFO] [1704516887.854050245, 1122.697000000]: Planner configuration 'manipulator_i5[RRTConnect]' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ WARN] [1704516887.855318768, 1122.698000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.855395733, 1122.698000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.855496989, 1122.698000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.855550441, 1122.698000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.855833115, 1122.699000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.855890426, 1122.699000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.856061280, 1122.699000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.856116315, 1122.699000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.856359269, 1122.699000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.001303 seconds
[ WARN] [1704516887.856816406, 1122.700000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.856866460, 1122.700000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.857047357, 1122.700000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.857489865, 1122.701000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.857718854, 1122.701000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.857760368, 1122.701000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.857896512, 1122.701000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.857938177, 1122.701000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.858068404, 1122.701000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.001306 seconds
[ WARN] [1704516887.858555270, 1122.702000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.858605655, 1122.702000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.858664099, 1122.702000000]: manipulator_i5[RRTConnect]: Skipping invalid start state (invalid state)
[ERROR] [1704516887.858801031, 1122.702000000]: manipulator_i5[RRTConnect]: Motion planning start tree could not be initialized!
[ WARN] [1704516887.858934388, 1122.702000000]: ParallelPlan::solve(): Unable to find solution by any of the threads in 0.000469 seconds
[ WARN] [1704516887.864125639, 1122.707000000]: Goal sampling thread never did any work.
[ INFO] [1704516887.864518553, 1122.708000000]: Unable to solve the planning problem
```
![image](https://github.com/AuboRobot/aubo_ros_driver/assets/130347165/106181ec-980c-466b-a1c2-624edb0be72a)

**Comment by JI-PENG264** [comment]
问题已经修改，可以更新一下仓库试一下

**Comment by dashuaip** [comment]
> 问题已经修改，可以更新一下仓库试一下

谢谢，现在仿真aubo-i5已经可以用了，而且把模型换成aubo-i10也没有问题。
现在我想测试一下连接真实机械臂的情况，请问现在aubo-i10可以用吗？

**Comment by JI-PENG264** [comment]
可以的，请先确认您的真实机械臂的示教器使用的是我们最新的ARCS系统

**Comment by dashuaip** [comment]
> 可以的，请先确认您的真实机械臂的示教器使用的是我们最新的ARCS系统

你好，我的示教器使用的是auboPE系统，ARCS是最新的示教器系统吗？有没有网页或资料可以让我下载ARCS？

**Comment by JI-PENG264** [comment]
https://docs.aubo-robotics.cn/application_notes/08-aubope-upgrade-arcs/
这是升级文档，您可以看一下

**Comment by dashuaip** [comment]
> https://docs.aubo-robotics.cn/application_notes/08-aubope-upgrade-arcs/
> 这是升级文档，您可以看一下

好的谢谢

**Comment by dlf12** [comment]
> https://docs.aubo-robotics.cn/application_notes/08-aubope-upgrade-arcs/ 这是升级文档，您可以看一下

你好，请问PE升级成ARCS有型号限制吗？我用的是i5，但是售后那边说型号太老了升不了
